apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: prometheus-kafka-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-kafka-exporter
    spec:
      restartPolicy: Always
      containers:
        - name: kafka-exporter
          image: dockeryounger123/common_exporter:v1.1_kafka_v1.2.0
          command:
            - /common_exporter
            - -logtostderr
            - -v=2
            - -exporter-bin-file=/kafka_exporter
            - -exporter-listen-addr=--web.listen-address=:%d
            - -exporter-monitor-addr=--kafka.server=%s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 10Mi