apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-server
subsets:
  - addresses:
      - ip: 1.2.3.4
    ports:
      - port: 9092
        name: kafka-port
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka-port